document.querySelectorAll(".form-note").forEach(el=>el.remove());

/* Assistara first-touch acquisition attribution. A tagged visitor keeps the original campaign for 30 days. */
(()=>{const endpoint='https://jhmmwleejgidrxavzdlq.supabase.co/functions/v1/track-acquisition',p=new URLSearchParams(location.search),incoming=(p.get('ref')||'').trim().toUpperCase(),key='assistara_acquisition';let saved=null;try{saved=JSON.parse(localStorage.getItem(key)||'null')}catch{}if(saved&&Date.now()-Number(saved.saved_at||0)>2592000000){localStorage.removeItem(key);saved=null}if(incoming&&!saved){const visitor=localStorage.getItem('assistara_visitor_id')||crypto.randomUUID(),session=sessionStorage.getItem('assistara_session_id')||crypto.randomUUID();localStorage.setItem('assistara_visitor_id',visitor);sessionStorage.setItem('assistara_session_id',session);fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:incoming,visitor_id:visitor,session_id:session,landing_path:location.pathname,referrer:document.referrer})}).then(r=>r.json()).then(x=>{if(x.ok)localStorage.setItem(key,JSON.stringify({token:x.token,visit_id:x.visit_id,destination:x.destination,saved_at:Date.now()}))}).catch(()=>{})}window.AssistaraAttribution={get(){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}},token(){return this.get()?.token||''},visitId(){return this.get()?.visit_id||''}}})();

const favicon=document.querySelector('link[rel="icon"]')||document.createElement('link');
favicon.rel='icon';favicon.type='image/svg+xml';favicon.href='/assistara-logo.svg?v=6';
if(!favicon.parentNode)document.head.appendChild(favicon);
const shortcutFavicon=document.querySelector('link[rel="shortcut icon"]')||document.createElement('link');shortcutFavicon.rel='shortcut icon';shortcutFavicon.type='image/svg+xml';shortcutFavicon.href='/assistara-logo.svg?v=6';if(!shortcutFavicon.parentNode)document.head.appendChild(shortcutFavicon);
const criticalMobileStyles=document.createElement('style');criticalMobileStyles.textContent=`.objection-wrap{display:none!important}.success{display:none!important}.mobile-academy-cta{display:none!important}#savingsCalculator .calc-control[for="delegateRange"],#savingsCalculator .calc-result-highlight{display:none!important}.assistara-footer-brand .brand{display:inline-flex!important;align-items:center!important;gap:10px!important;width:max-content!important}.assistara-footer-brand .brand .mark{width:42px!important;height:42px!important;flex:0 0 42px!important;object-fit:contain!important;object-position:center!important}@media(max-width:760px){html,body{width:100%!important;max-width:100%!important;overflow-x:hidden!important}.announcement,.mobile-academy-cta,.logo-strip,.float-card,.nav-links,.nav>.btn,.nav .btn-small{display:none!important}.site-header{padding:10px 0!important;background:rgba(251,250,246,.97)!important}.site-header .shell{width:calc(100% - 28px)!important}.nav{min-height:60px!important;margin:0!important;border-radius:20px!important;padding:9px 14px!important}.nav .brand{font-size:19px!important;gap:9px!important}.nav .mark{width:34px!important;height:34px!important}.hero{display:block!important;max-width:100%!important;padding:42px 0 70px!important;overflow:hidden!important}.hero-copy{min-width:0!important;max-width:100%!important}.hero .eyebrow,.hero-proofline{display:none!important}.hero h1{font-size:clamp(54px,15vw,68px)!important;line-height:.94!important;letter-spacing:-.06em!important;margin:0 0 24px!important;max-width:360px!important}.hero h1 span:after{height:12px!important;bottom:1px!important}.hero-sub{font-size:18px!important;line-height:1.5!important;color:#5f5b57!important;max-width:390px!important;margin:0!important}.hero-actions{display:block!important;margin-top:30px!important}.hero-actions .btn{width:100%!important;min-height:58px!important;font-size:17px!important;padding:17px 22px!important}.hero-actions .text-link,.trust-row,.hero-visual{display:none!important}}`;document.head.appendChild(criticalMobileStyles);
for(const brand of document.querySelectorAll('.brand'))brand.innerHTML=`<img class="mark" src="/assistara-logo.svg" alt=""><span>Assistara</span>`;
if(window.matchMedia('(max-width:760px)').matches){document.querySelectorAll('.mobile-academy-cta').forEach(el=>el.remove());const heroSub=document.querySelector('.hero-sub');if(heroSub)heroSub.textContent='Delegate the repeatable work. Keep your time for what moves the business forward.'}
const LEAD_ENDPOINT='https://jhmmwleejgidrxavzdlq.supabase.co/functions/v1/website-form-proxy';const form=document.getElementById('leadForm'),success=document.getElementById('successMessage');if(form&&success){form.querySelector('.form-note')?.remove();const button=form.querySelector('button[type="submit"]');success.hidden=true;success.style.setProperty('display','none','important');success.innerHTML='<b>Request received. We’ll be in touch soon.</b>';form.addEventListener('submit',async event=>{event.preventDefault();const fd=new FormData(form),original=button.textContent;button.textContent='Sending…';button.disabled=true;success.hidden=true;success.style.setProperty('display','none','important');try{const response=await fetch(LEAD_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'b2b',name:fd.get('name')||'',email:fd.get('email')||'',company:fd.get('company')||'',time_thieves:fd.get('tasks')||'',support_level:fd.get('hours')||'Not sure yet',tracking_token:window.AssistaraAttribution?.token()||'',acquisition_visit_id:window.AssistaraAttribution?.visitId()||''})});const result=await response.json().catch(()=>({}));if(!response.ok||!result.ok||!result.emailSent)throw new Error('Submission or email delivery failed');button.textContent='Request sent ✓';success.hidden=false;success.style.setProperty('display','flex','important');form.reset();success.scrollIntoView({behavior:'smooth',block:'nearest'})}catch(error){button.textContent=original;button.disabled=false;success.innerHTML='<b>Couldn’t send that yet.</b><span>Please try again in a moment.</span>';success.hidden=false;success.style.setProperty('display','flex','important')}})}
const navLinks=document.querySelector('.nav-links');if(navLinks&&!navLinks.querySelector('[href="/academy"]')){const a=document.createElement('a');a.href='/academy';a.textContent='Become a Virtual Assistant';navLinks.appendChild(a)}
const objection=document.querySelector('.objection-wrap');if(objection)objection.remove();
const siteFooter=document.querySelector('body > footer');if(siteFooter){siteFooter.innerHTML=`<div class="shell assistara-footer-main"><div class="assistara-footer-brand"><a class="brand" href="#top"><img class="mark" src="/assistara-logo.svg" alt=""><span>Assistara</span></a><p>Buy back your time. More room to grow. More freedom to live.</p></div><div class="assistara-footer-links"><span>EXPLORE</span><a href="#how">How it works</a><a href="#roles">What you can delegate</a><a href="/academy">Assistara Academy</a></div><div class="assistara-footer-contact"><span>NEED HELP?</span><a class="assistara-email" href="mailto:support@getassistara.com">support@getassistara.com <b>↗</b></a><a class="assistara-footer-cta" href="/academy">Become a Virtual Assistant <b>→</b></a></div></div><div class="shell assistara-footer-bottom"><span>© 2026 Assistara</span><span>Trained. Vetted. Matched around your work.</span></div>`}
