"use strict";

// reddit-pixel.test.js — Reddit Ads Pixel tracking for masterclass signups
//
// The Reddit Pixel is loaded via /reddit-pixel.js on all public pages.
// The Lead event fires from academy.html inside the masterclass form's
// success handler, only after the backend has confirmed registration.
//
// This test suite verifies:
//   1. The pixel script is included on public pages.
//   2. The Lead event fires with the correct Pixel ID.
//   3. conversionId is derived from attendeeToken (stable, backend-issued).
//   4. Email is passed for advanced matching when consent exists.
//   5. No Lead fires on failed submissions.
//   6. Google Ads conversion still fires correctly.
//   7. No duplicate global pixel tags.

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");
const PIXEL_ID = "a2_jte0nyi9n43d";

const read = (name) => fs.readFileSync(path.join(ROOT, name), "utf8");
const countIn = (haystack, needle) => haystack.split(needle).length - 1;

test("reddit-pixel.js exists and contains the correct Pixel ID", () => {
  const pixel = read("reddit-pixel.js");
  assert.ok(pixel.includes(`pixel_id=${PIXEL_ID}`), "Pixel ID must match a2_jte0nyi9n43d");
  assert.ok(pixel.includes("rdt('init','a2_jte0nyi9n43d')"), "init must use correct ID");
  assert.ok(pixel.includes("rdt('track','PageVisit')"), "PageVisit must fire on load");
});

test("reddit-pixel.js exports consent-aware trackLead helper", () => {
  const pixel = read("reddit-pixel.js");
  assert.ok(pixel.includes("AssistaraReddit"), "must expose AssistaraReddit namespace");
  assert.ok(pixel.includes("trackLead"), "must expose trackLead function");
  assert.ok(pixel.includes("conversionId"), "trackLead must accept conversionId");
  assert.ok(pixel.includes("assistara_ads_consent"), "must check consent cookie");
  assert.ok(pixel.includes("hasConsent"), "must have hasConsent helper");
});

test("academy.html includes the Reddit Pixel script exactly once", () => {
  const academy = read("academy.html");
  assert.equal(countIn(academy, "/reddit-pixel.js"), 1, "academy.html must include reddit-pixel.js exactly once");
  assert.ok(academy.includes("<script src=\"/reddit-pixel.js\"></script>"), "script tag must be present");
});

test("index.html includes the Reddit Pixel script exactly once", () => {
  const index = read("index.html");
  assert.equal(countIn(index, "/reddit-pixel.js"), 1, "index.html must include reddit-pixel.js exactly once");
  assert.ok(index.includes("<script src=\"/reddit-pixel.js\"></script>"), "script tag must be present");
});

test("masterclass form handler fires Reddit Lead on success with conversionId", () => {
  const academy = read("academy.html");
  // The Lead event must fire in the success path, after Google Ads conversion
  assert.ok(academy.includes("window.AssistaraReddit?.trackLead"),
    "must call AssistaraReddit.trackLead in success handler");
  assert.ok(academy.includes("result.attendeeToken"),
    "conversionId must come from backend-issued attendeeToken");
  assert.ok(academy.includes("data.get('email')"),
    "email must be passed for advanced matching");
  assert.ok(academy.includes("catch(redditConversionError)"),
    "Reddit tracking errors must be swallowed");
});

test("Reddit Lead fires after Google Ads conversion in the same try block", () => {
  const academy = read("academy.html");
  const gtagIdx = academy.indexOf("window.gtag==='function'");
  const redditIdx = academy.indexOf("window.AssistaraReddit?.trackLead");
  const catchIdx = academy.indexOf("catch(redditConversionError)");
  const handlerCatchIdx = academy.indexOf("catch(error){console.error('Masterclass signup failed:'");
  
  assert.ok(gtagIdx > -1, "Google Ads conversion must exist");
  assert.ok(redditIdx > -1, "Reddit Lead must exist");
  assert.ok(gtagIdx < redditIdx, "Reddit Lead must fire after Google Ads conversion");
  assert.ok(redditIdx < catchIdx, "Reddit Lead must be inside the try block");
  assert.ok(redditIdx < handlerCatchIdx, "Reddit Lead must not be reachable from error path");
});

test("Reddit Lead conversionId uses stable attendeeToken from backend", () => {
  const academy = read("academy.html");
  // The attendeeToken is generated by the backend (website-form function)
  // and returned in the success response. This ensures:
  // - Same registration = same conversionId (deduplication)
  // - Different registration = different conversionId
  // - Retries/reloads use the same token from localStorage or response
  assert.ok(academy.includes("result.attendeeToken"),
    "conversionId must be the backend-issued attendeeToken");
  // The trackLead call should pass attendeeToken as conversionId
  assert.ok(academy.includes("trackLead(result.attendeeToken"),
    "trackLead must receive attendeeToken as conversionId");
  // Should not generate a fresh UUID for conversionId in the trackLead call
  const trackLeadIdx = academy.indexOf("trackLead(");
  const afterTrackLead = academy.slice(trackLeadIdx, trackLeadIdx + 200);
  assert.ok(!afterTrackLead.includes("crypto.randomUUID()"),
    "trackLead call must not generate a fresh UUID for conversionId");
});

test("advanced matching: email passed only when consent exists", () => {
  const pixel = read("reddit-pixel.js");
  assert.ok(pixel.includes("hasConsent() && email"),
    "email must only be included when consent is granted");
  assert.ok(pixel.includes("window.AssistaraConsent?.hasConsented"),
    "consent check must use AssistaraConsent API");
});

test("no duplicate pixel initialisation (idempotent)", () => {
  const pixel = read("reddit-pixel.js");
  assert.ok(pixel.includes("if(w.rdt)return"),
    "must bail out if rdt already exists");
  // Should only have one rdt('init') call
  assert.equal(countIn(pixel, "rdt('init'"), 1, "init must be called exactly once");
});

test("vercel.json includes reddit-pixel.js build and route", () => {
  const vercel = JSON.parse(read("vercel.json"));
  const hasBuild = vercel.builds.some(b => b.src === "reddit-pixel.js");
  const hasRoute = vercel.routes.some(r => r.src === "/reddit-pixel.js");
  assert.ok(hasBuild, "vercel.json must have build entry for reddit-pixel.js");
  assert.ok(hasRoute, "vercel.json must have route entry for /reddit-pixel.js");
});

test("no second Reddit pixel tag anywhere on site", () => {
  const htmlFiles = fs.readdirSync(ROOT).filter(f => f.endsWith(".html"));
  for (const file of htmlFiles) {
    const html = read(file);
    const redditstaticCount = (html.match(/redditstatic\.com/g) || []).length;
    assert.ok(redditstaticCount <= 1, `${file} must not have more than one Reddit pixel script`);
  }
});

test("Google Ads conversion unchanged by Reddit integration", () => {
  const academy = read("academy.html");
  assert.ok(academy.includes("AW-341289722/iY7ICN6ehpUdEPrV3qIB"),
    "Google Ads send_to must remain unchanged");
  assert.ok(academy.includes("gtag('event','conversion'"),
    "Google Ads conversion call must remain");
});

test("Reddit Pixel only initialised once per page load (no client-side router)", () => {
  const pixel = read("reddit-pixel.js");
  // The site uses full document loads, so the script runs once per page
  // The idempotent check prevents double-init even if script included twice
  assert.ok(pixel.includes("This site has no client-side router"),
    "documentation must note no client-side router");
});